### ISSUE TITLE
Bump minimum rust to 1.31 to add clippy and rustfmt attributes to each of the modules

### ISSUE THREAD

**Issue by na-g** [mozilla/webrtc-sdp#127]
One can add rustfmt and clippy attributes, e.g. `#![warn(clippy::all)]`, to modules to make sure that the compiler runs those tools. These are only available in Rust 1.31+. We just semi-arbitrarily bumped to Rust 1.30, and it would be an easy time to bump to 1.31 so that we can have this automated tooling.

**Comment by na-g** [comment]
See the Rust 1.31 release notes https://blog.rust-lang.org/2018/12/06/Rust-1.31-and-rust-2018.html#tool-lints

**Comment by nils-ohlmeier** [comment]
That sounds like a useful feature, as I have burned quite a few CI hours forgetting to do the code formatting or the clippy checks.

My only concern is is we should release a 0.2.0 crate before or after bumping the min rust version again.

**Comment by na-g** [comment]
See #128

**Comment by na-g** [comment]
We will be going with Rust 1.3.5.
