### ISSUE TITLE
Add RTCP-MUX support

### ISSUE THREAD

**Issue by na-g** [mozilla/webrtc-sdp#185]
We need to add support for RTCP-MUX, e.g. `a=rtcp-mux`.

**Comment by nils-ohlmeier** [comment]
@na-g I'm confused: rtcp-mux is already supported https://github.com/mozilla/webrtc-sdp/blob/master/src/attribute_type.rs#L4041

What makes you think it's not supported yet?

**Comment by na-g** [comment]
Sorry, this was an off by one error when looking at a diff. It is clearly in the tree.
