### ISSUE TITLE
ice-lite SDP parsing error on hangouts and meet

### ISSUE THREAD

**Issue by dminor** [mozilla/webrtc-sdp#208]
Noticed this on both hangouts and meet:

Error parsing SDP in rust: Sequence error in line(17): Parsing error: ice-lite not allowed at media level

I was testing window sharing, but I think the error was showing up prior to sharing a window.

**Comment by nils-ohlmeier** [comment]
Ugh :-(

I guess we should file an issue with them to get it fixed on their end.

The question is if we need to accept this until they fix it, or at least only turn it into warning.

**Comment by timwinchester** [comment]
I've merged a fix for this to Hangouts and Meet, and it should hit production before the end of the month.

**Comment by na-g** [comment]
@timwinchester, thank you for the update!
