### ISSUE TITLE
SDP parsing error

### ISSUE THREAD

**Issue by ximex** [mozilla/webrtc-sdp#217]
I got following error in the console if i start firefox from the console and open a WebRTC connection i'm currently working on. Not sure if it is a bug of this lib or the signaling server sends something wrong, but didn't get an error on Firefox stable
```
[2020-04-21T11:50:07Z ERROR rsdparsa_capi] Error parsing SDP in rust: Line error: Integer parsing error: cannot parse integer from empty string in line(22): a=fmtp:0 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=
```

OS: Kubuntu 19.10
FIrefox: 77.0a1 2020-04-21

**Comment by na-g** [comment]
@ximex it looks like the `profile-level-id` is empty in the line above. I do not believe that is allowed to be empty. If one wants the default profile, `profile-level-id` should be omitted all together.

**Comment by na-g** [comment]
The error message could be improved in the general case of missing parameter values.

**Comment by ximex** [comment]
ok you are right. the `profile-level-id` is missing. i don't know why i have not seen that.
