### ISSUE TITLE
Crates.io release

### ISSUE THREAD

**Issue by dtzxporter** [mozilla/webrtc-sdp#265]
Any chance we can get a release pushed to crates.io? There are a few changes that have been on master for a bit that we would like to use w/o having to link to the github directly.

**Comment by lerouxrgd** [comment]
Hello @nils-ohlmeier , are there any plan to publish lastest master on crates.io ?

**Comment by lerouxrgd** [comment]
@dtzxporter Version `0.3.10` has been released on crates.io
