### ISSUE TITLE
Should we use travis-cargo

### ISSUE THREAD

**Issue by nils-ohlmeier** [mozilla/webrtc-sdp#35]
Looks like travis-cargo could simplify the travis.yaml file quite a bit https://github.com/huonw/travis-cargo

**Comment by luser** [comment]
FYI I've used travis-cargo in a few projects and I didn't find it to be a huge improvement. Wrapping the kcov build is nice, although I did have to work around a travis-cargo bug with uploading to coveralls:
https://github.com/luser/read-process-memory/blob/master/.travis.yml

**Comment by nils-ohlmeier** [comment]
I think switching to tarpaulin made the code coverage topic quite a bit easier. And we don't see to have too many problems with managing the travis yaml files directly. So I think we can close this.
